version: "3.8"

services:
  postgres:
    image: postgres:14.5
    container_name: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - product-management

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
      - "3001:3000"
    networks:
      - product-management

networks:
  product-management:
    driver: bridge

volumes:
  postgres:
